#
#  PROGRAM:   Assignment 1
#  AUTHOR:    Anushka Verma
#  LOGON ID:  Z1911937
#  DUE DATE:  02/05/2022
#
CCFLAGS = -Wall -std=c++11

z1911937_project1: z1911937_project1.o
	g++ $(CCFLAGS) -o z1911937_project1 z1911937_project1.o

z1911937_project1.o: z1911937_project1.cc
	g++ $(CCFLAGS) -c z1911937_project1.cc

clean:
	-rm *.o z1911937_project1