#
# PROGRAM: Bitwise Operators & IEEE-754 Floating Point Number Decoding
# AUTHOR:  Anushka Verma (Z1911937)
#

CXXFLAGS = -Wall -Werror -std=c++11

prog2: prog2.o
	g++ $(CXXFLAGS) -o prog2 prog2.o

prog2.o: prog2.cpp
	g++ $(CXXFLAGS) -c prog2.cpp

clean:
	rm -f *.o prog2