#
#  PROGRAM:   Assignment 2
#  AUTHOR:    Anushka Verma
#  LOGON ID:  Z1911937
#  DUE DATE:  02/19/2022
#
CCFLAGS = -w -Wall -std=c++11

z1911937_project2: z1911937_project2.o
	g++ $(CCFLAGS) -o z1911937_project2 z1911937_project2.o

z1911937_project2.o: z1911937_project2.cc
	g++ $(CCFLAGS) -c z1911937_project2.cc

clean:
	-rm *.o z1911937_project2