#
#  PROGRAM:   Assignment 4
#  AUTHOR:    Anushka Verma
#  LOGON ID:  Z1911937
#  DUE DATE:  03/29/2022
#  EXTENSION: 04/05/2022
#
z1911937_project3:
	g++ -std=c++11 -Wall -Wextra -pedantic -o z1911937_project3 main.cc
clean:
	rm -f z1911937_project3